HaneenStore/Models/Auther.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;


namespace HaneenStore.Models
{
    [Index(nameof(AutherName), IsUnique = true)]

    public class Auther
    {
        public int Id { get; set; }
        public string AutherName { get; set; } = null!;
        public DateTime CreatedOn { get; set; } = DateTime.Now;
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
    }
}

HaneenStore/Controllers/AutherController.cs
using HaneenStore.Data;
using Microsoft.AspNetCore.Mvc;
using HaneenStore.ViewModel;
using HaneenStore.Models;
using Microsoft.AspNetCore.Http.HttpResults;
namespace HaneenStore.Controllers
{
    public class AutherController : Controller
    {
        ApplicationDbContext context;

        public AutherController(ApplicationDbContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var authers = context.Authers.ToList();
            var authersVm = authers.Select(auther => new AutherVm
            {
                Id = auther.Id,
                AutherName = auther.AutherName,
                CreatedOn = auther.CreatedOn,
                UpdatedOn = auther.UpdatedOn,

            }).ToList();
           

            return View("index",authersVm);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View("AutherForm");
        }
        [HttpPost]
        public IActionResult Create(AutherFormModel autherformmodel)
        {
            if (ModelState.IsValid)
            {
                var auther = new Auther
                {
                    AutherName = autherformmodel.AutherName
                };
                try
                {
                    context.Authers.Add(auther);
                    context.SaveChanges();
                    return RedirectToAction("index");

                }
                catch
                {
                    ModelState.AddModelError("AutherName", "Auther Name Already Exists");
                    return View("AutherForm");

                }

            }
            else
            {
                return View("AutherForm", autherformmodel);
            }


        }


        [HttpGet]
        public IActionResult Edit(int id)
        {

            var auther = context.Authers.Find(id);
            if (auther is null)
            {
                return NotFound();
            }
            else
            {
               

                var viewmodel = new AutherFormModel { Id = id, AutherName = auther.AutherName };
                return View("AutherForm", viewmodel);
            }
        }
        [HttpPost]
        public IActionResult Edit(int id, AutherFormModel autherformmodel)
        {
            if (!ModelState.IsValid)
            {
                return View("AutherForm", autherformmodel);
            }
            var auther = context.Authers.Find(autherformmodel.Id);
            if (auther is null)
            {
                return NotFound();
            }


            auther.AutherName = autherformmodel.AutherName;
            auther.UpdatedOn = DateTime.Now;
            context.SaveChanges();

            return RedirectToAction("index");
        }
        public IActionResult Details(int id)
        {
            var auther = context.Authers.Find(id);
            if (auther is null)
            {
                return NotFound();
            }
            else
            {
                var viewModle = new AutherVm { Id = id, AutherName = auther.AutherName };
                return View("Detailes", viewModle);

            }

        }
        public IActionResult Remove(int id)
        {
            var auther = context.Authers.Find(id);
            if (auther is null)
            {
                return NotFound();
            }
            context.Authers.Remove(auther);
            context.SaveChanges();
            return Ok();


        }

    }
}

HaneenStore/Views/Auther/AutherForm.cshtml
@using HaneenStore.ViewModel
@model AutherFormModel
@section Title{
    Authers
}
@section subTitle{
    @(Model?.Id == null ? "Create" : "Edit")
}
<form asp-controller="Auther" >
  <div class="mb-3">
        <label asp-for="AutherName"></label>
        <input type="text" class="form-control" asp-for="AutherName">
        <span asp-validation-for="AutherName" class="text-danger"></span>
  </div>


  <button type="submit" class="btn btn-primary">@(Model?.Id == null ? "Add" : "Update")</button>
</form>

HaneenStore/Views/Auther/Detailes.cshtml
@using HaneenStore.ViewModel
@model AutherVm
@section Title{
    Authers
}
@section subTitle{
    Show Details
}
<div class="card">
    <div class="card-header border-0">
        <div class="card-tools">
            <a href="#" class="btn btn-tool btn-sm">
                <i class="fas fa-download"></i>
            </a>
            <a href="#" class="btn btn-tool btn-sm">
                <i class="fas fa-bars"></i>
            </a>
        </div>
    </div>
    <div class="card-body table-responsive p-0">
        <table class="table table-striped table-valign-middle">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Created On</th>
                    <th>Updated On</th>


                </tr>
            </thead>
            <tbody>




                <tr>
                    <td>@Model.Id</td>
                    <td>@Model.AutherName</td>
                    <td>@Model.CreatedOn</td>
                    <td>@Model.UpdatedOn</td>



                </tr>





            </tbody>
        </table>
    </div>
</div>

HaneenStore/Views/Auther/Index.cshtml
@using HaneenStore.ViewModel
@model List<AutherVm>
@section Title{
    Autheres
}
@section subTitle{
    Auther Data
}
@section Button{
    <a asp-controller="Auther" asp-action="Create" class="btn btn-primary  "> Create</a>
}
@if (!Model.Any())
{
    <div class="col-md-12">
        <div class="card card-warning">
            <div class="card-header">
                <h3 class="card-title">No Data Found</h3>
            </div>


        </div>
        <!-- /.card -->
    </div>
}
else
{

    <div class="card">
        <div class="card-header border-0">
            <div class="card-tools">
                <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-download"></i>
                </a>
                <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-bars"></i>
                </a>
            </div>
        </div>
        <div class="card-body table-responsive p-0">
            <table class="table table-striped table-valign-middle">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Created On</th>
                        <th>Updated On</th>


                    </tr>
                </thead>
                <tbody>


                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>@item.Id</td>
                            <td>@item.AutherName</td>
                            <td>@item.CreatedOn</td>
                            <td>@item.UpdatedOn</td>
                            <td><a asp-asp-controller="Auther" asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-user-edit text-primary"></i></a></td>
                            <td><a asp-controller="Auther" asp-action="Details" asp-route-id="@item.Id" class="ps-5"><i class="fas fa-info-circle text-success"></i></a></td>
                            <td><a href="#" data-id="@item.Id" class="ps-5 js-delete "><i class="fas fa-trash-alt text-danger "></i></a></td>



                        </tr>

                    }




                </tbody>
            </table>
        </div>
    </div>

}
@section Scripts{
    <script>

        document.querySelectorAll(".js-delete").forEach((btn) => {
            btn.addEventListener("click", async () => {
                Swal.fire({
                    title: "Are you sure?",
                    text: "You won't be able to revert this!",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Yes, delete it!"
                }).then(async (result) => {
                    if (result.isConfirmed) {
                        const id = btn.getAttribute("data-id");
                        // const id= btn.getAttribute("data-id");
                        console.log(id);
                        const response = await fetch(`/Auther/Remove/${id}`, { method: 'Post' });
                        if (response.ok) {
                            btn.closest("tr").remove();
                            const Toast = Swal.mixin({
                                toast: true,
                                position: 'top-end',
                                iconColor: 'white ',
                                customClass: {
                                    popup: 'colored-toast',

                                },
                                showConfirmButton: false,
                                timer: 2500,
                                timerProgressBar: true,

                            })
                            Toast.fire({
                                icon: 'success',
                                title: 'Auther Deleted Successfully',
                            })
                        }
                    }
                });


            })
        })




    </script>
}